spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/syntaxmath
    username: syntaxmath
    password: syntaxmath
  data:
    redis:
      host: localhost
      port: 6379
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: openai/gpt-oss-120b
